@startuml
hide empty description

state MAPPING: update workspace
MAPPING: collision check
MAPPING-->MAPPING

state LOCALPLANNING: wait call
LOCALPLANNING: plan
LOCALPLANNING: publish trajectory
LOCALPLANNING-->LOCALPLANNING

state MISSION: control the mav traveling waypoints
state MISSION{

    state READY: on land
    READY: set home

    state MANUALFLIGHT: flight under non-OFFBOARD
    ' MANUALFLIGHT: if enter OFFBOARD, preprocess waypoints

    state AUTOFLIGHT: work under armming and OFFBORAD mode
    state AUTOFLIGHT{
        state GEN_NEW_TRAJ: chose target from waypoints
        GEN_NEW_TRAJ: set current state as start state
        GEN_NEW_TRAJ: call replan via sending start and target state

        state WAIT_TRAJ: wait planner result
        WAIT_TRAJ: if come from GEN_NEW_TRAJ, send zero
        WAIT_TRAJ: if come from REPLAN_TRAJ, send cmds from planned trajectory
        WAIT_TRAJ: if waiting too long time, break

        state EXEC_TRAJ: send cmds
        EXEC_TRAJ: check if need replan and reach end

        state REPLAN_TRAJ: chose target from waypoints
        REPLAN_TRAJ: get start state from trajectory
        REPLAN_TRAJ: call replan via sending start and target state

        [*]-[#green,bold]-->GEN_NEW_TRAJ: no traj
        [*]-[#red,bold]-->REPLAN_TRAJ: collision

        GEN_NEW_TRAJ-[#green,bold]->WAIT_TRAJ
        ' WAIT_TRAJ-[#green,bold]->GEN_NEW_TRAJ: plan failed

        WAIT_TRAJ-[#green,bold]->EXEC_TRAJ: receive traj
        EXEC_TRAJ-[#green,bold]->REPLAN_TRAJ: over duration/distance

        REPLAN_TRAJ-[#green,bold]->WAIT_TRAJ

        EXEC_TRAJ-[#green,bold]->[*]: reach end     

        state FAULT 
    }



    ' [*] -[#green,bold]-> IDLE: initialization
    [*]-->READY
    READY --> MANUALFLIGHT: armming
    MANUALFLIGHT-->READY: disarmming
    ' MANUALFLIGHT --> MANUALFLIGHT
    MANUALFLIGHT --> AUTOFLIGHT: OFFBOARD
    AUTOFLIGHT --> MANUALFLIGHT: non-OFFBOARD
    AUTOFLIGHT --> READY: disarmming

}

state fork_state <<fork>>
[*]-->fork_state
fork_state-[#green,bold]->MISSION
fork_state-[#green,bold]->MAPPING
fork_state-[#green,bold]->LOCALPLANNING

' MAPPING-[#red,bold]->REPLAN_TRAJ

@enduml