%YAML:1.2
---
PlanMap:
  resolution: 0.2
  sogm_size_x: 20
  sogm_size_y: 20
  sogm_size_z: 10
  p_hit: 0.80
  p_miss: 0.35
  p_min: 0.12
  p_max: 0.97
  p_occ: 0.80

  useSquareDist: 0 # 0 = false, 1=true
  esdf_max_xy: 4.0 # (m)
  esdf_max_z: 4.0 # (m)

DepthCamera:
  heigth: 480 # /realsense_plugin/camera/depth/image_raw
  width: 640
  fx: 554.3826904296875
  fy: 554.3826904296875
  cx: 320.0
  cy: 240.0

  # heigth: 640 # /camera/depth/image_rect_raw
  # width: 480
  # fx: 392.365234375
  # fy: 392.365234375
  # cx: 320.01055908203125
  # cy: 241.12890625

  k_depth_scaling_factor: 1000
  depth_maxdist: 10.0
  depth_mindist: 0.5
  depth_filter_margin: 10
  skip_pixel: 4

  R_C_2_B: !!opencv-matrix #normal realsense
    rows: 3
    cols: 3
    dt: d
    data: [0, 0, 1, -1, 0, 0, 0, -1, 0]

  T_C_2_B: !!opencv-matrix  # !! explicity specify the type
    rows: 1
    cols: 3
    dt: d
    data: [0.0, 0.0, 0.0]

Astar:
  resolution: 0.5
  min_dist: 2.0
  pool_size_x: 100 # res
  pool_size_y: 100
  pool_size_z: 100

PathNlopt:
  max_vel: 3.0 # 会被目标点覆盖
  max_acc: 2.0
  min_dist: 2.5
  lambda_smoothness: 10.0
  lambda_feasibility: 0.0001
  lambda_distance: 5.0
  max_iteration_num: 500
  max_iteration_time: 0.05
